theme: minima

header_pages:
  - index.md
  - image01.md
  - graphics02.md
  - downloads.md
  - ipage.md
  - scriptpractice.md

 #remote_theme: pages-themes/architect@v0.2.0
 #plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
author: Bob K
description: Fill the world with irony and nonsense - 2 of my few talents 
sass:
  sass_dir: _sass
  style: compressed

