theme: minima
favicon: /assets/PassageFavIcon.png
header_pages:
  - index.md
  - image01.md
  - image02.md
  - graphics02.md
  - downloads.md
  - media.md
  - ipage.md
  - scriptpractice.md
#defaults:
#  -
#    scope:
#      path: ""
#    values:
#      layout: "base-with-notification"

#in header_pages the filenames listed are those in the project/on disk - titles within the files are what appear on pages
#remote_theme: pages-themes/architect@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
author: Bob K
description: Fill the world with irony and nonsense - 2 of my few talents 
sass:
  sass_dir: _sass
  style: compressed

